# WARNING ! this file has been generated by generate_slow_containers.py.
from numpy import ndarray, uint8, int64, int32, float32, float64
from astropy import units as u
from ctapipe.core import Container, Field

__all__ = [
    "SlowDataContainer",
    "fill_slow",
]


class SlowDataContainer(Container):
    safetyplc = Field(None, "SafetyPLC")
    pdpslowcontrol = Field(None, "PDPSlowControl")
    digicamslowcontrol = Field(None, "DigicamSlowControl")
    mastersst1m = Field(None, "MasterSST1M")
    drivesystem = Field(None, "DriveSystem")


def fill_slow(class_name, event, hdu, slow_event):
    if class_name == "SafetyPLC":
        event = fill_SafetyPLC(event, hdu, slow_event)
    elif class_name == "PDPSlowControl":
        event = fill_PDPSlowControl(event, hdu, slow_event)
    elif class_name == "DigicamSlowControl":
        event = fill_DigicamSlowControl(event, hdu, slow_event)
    elif class_name == "MasterSST1M":
        event = fill_MasterSST1M(event, hdu, slow_event)
    elif class_name == "DriveSystem":
        event = fill_DriveSystem(event, hdu, slow_event)
    else:
        print("ERROR in fill_slow(): class %s not known." % class_name)
        print("Try to regenerate slow data containers ?")
    return event
